# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "base"

  config.vm.host_name = "atmessager"

  config.vm.network :public_network

  config.vm.synced_folder "../../ATMessager", "/opt/nx/atmessager", create: true, group: "www-data", owner: "www-data"

  config.vm.provider "virtualbox" do |vb|
    vb.customize [ "modifyvm", :id, "--memory", 1024]
    vb.customize [ "modifyvm", :id, "--name", "atmessager"]
  end

  config.vm.provision "chef_solo" do |chef|
  chef.cookbooks_path = ["cookbooks"]
  chef.add_recipe "atmessager::default"
  end
end
